### ISSUE TITLE
Vertical layout behavior

### ISSUE THREAD

**Issue by carterhudson** [Yummypets/Stevia.kt#1]
When trying to lay out views, I want to achieve something that looks like this:
<img width="310" alt="Screen Shot 2019-10-01 at 11 07 23 AM" src="https://user-images.githubusercontent.com/2574098/65984070-2ca9b180-e43c-11e9-98f6-5d529fa7c09e.png">

The following code achieves what I want:
```
    proteinLabel.centerInParent()

    fatLabel
      .constrainRightToRightOf(proteinLabel)
      .constrainBottomToTopOf(proteinLabel, 40)

    carbLabel
      .constrainRightToRightOf(proteinLabel)
      .constrainTopToBottomOf(proteinLabel, 40)
```
 But I like how visually intuitive the `layout()` function is. I would expect something like
```
layout(
      "",
      fatLabel.constrainRightToRightOf(proteinLabel),
      40,
      I - proteinLabel.centerVertically() - I,
      40,
      carbLabel.constrainRightToRightOf(proteinLabel),
      ""
    )
```
would achieve the same result as the first snippet, but that doesn't seem to be the case. Instead, I get the following:
<img width="314" alt="Screen Shot 2019-10-01 at 11 14 35 AM" src="https://user-images.githubusercontent.com/2574098/65984374-de48e280-e43c-11e9-97ff-f656edea35e7.png">
Is there a way to achieve the layout I'm after using the `layout()` method? Otherwise, I don't know that I gain a whole lot over the visual design representation, especially as the number of subviews grows and increases the complexity and number of constraints.

For example, creating a view like this doesn't seem to be easy with Stevia:
<img width="316" alt="Screen Shot 2019-10-01 at 12 13 55 PM" src="https://user-images.githubusercontent.com/2574098/65988489-2e2ba780-e445-11e9-807a-afc5fb9ea4c0.png">
Whereas it's simple with the design editor:
<img width="578" alt="Screen Shot 2019-10-01 at 12 16 19 PM" src="https://user-images.githubusercontent.com/2574098/65988583-50bdc080-e445-11e9-9869-633a619578ca.png">

**Comment by s4cha** [comment]
Hi @carterhudson 

The following is how we'd ideally like to write your example. :
```kotlin
layout(
    fatLabel.constrainRightToRightOf(proteinLabel),
    40,
    proteinLabel.centerInParent(),
    40,
    carbLabel.constrainRightToRightOf(proteinLabel)
)
```

unfortunately this translates into

```kotlin
fatLabel.constrainRightToRightOf(proteinLabel)
proteinLabel.centerInParent()
                     .constrainTopToBottomOf(fatLabel, 40)
carbLabel.constrainRightToRightOf(proteinLabel)
                 .constrainTopToBottomOf(proteinLabel, 40)
```

The problem is that using  the visual `layout` helper, constraints are appplied in a top-down fashion. Meaning `proteinLabel` is placed relative to `fatLabel` instead of the contrary. This essentially comes from the fact that ConstraintLayout constraints are **not** reflexive. Which is a big pain in my opinion (it's not like that on iOS's Autolayout for example). This creates tricky cases. 


If you find a solution, I am all ears :)

By the way I think the way forward is now to start using https://developer.android.com/jetpack/compose :)

PS: Please excuse the late reply

**Comment by s4cha** [comment]
Concerning the last example, you might be able to create a `Guideline` programatically.
The rationale is that anything that's available through the Visual editor should be able to be done in code. However I find ConstraintLayout documentation to be very poor, it really seems like they don't want us to do this in code xD.
